# -*- coding: utf-8 -*-
"""All_factors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpWf0ZfdWaCDyKG32djoBat89UpBwJ79
"""

def factors(n):
  factorlist = []
  for i in range(1,n+1):
    if n%i == 0:
      factorlist = factorlist + [i]
  return(factorlist)

