# -*- coding: utf-8 -*-
"""Binary_Search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N2Y8vDbphXDsRF-hxlj6o2NSZ1xloHiw
"""

def bsearch(seq,v,l,r):
  # Search for v in seq[l:r], seq is sorted
  if r-l == 0:
    return False
  mid = (l+r)//2 #integer-division
  if v==seq[mid]:
    return True
  if v<seq[mid]:
    return (bsearch(seq,v,l,mid))
  else:
    return (bsearch(seq,v,mid+1,r))

# l=[1,3,2,5,2,9]
# v=2
#bsearch(l,v,0,6)

