# -*- coding: utf-8 -*-
"""Dynamic_Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BKk6lYEeGTFgG2xrOEtK6jGO1eAhTw9F
"""

def fib(n):
  fibtable =[0,1]
  for i in range(2,n+1):
    fibtable.append(fibtable[i-1] + fibtable[i-2])
  return fibtable[n]

