# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BKk6lYEeGTFgG2xrOEtK6jGO1eAhTw9F
"""

def fib(n):
  if n==0 or n==1:
    value = n
  else:
    value = fib(n-1) + fib(n-2)
  return value

