# -*- coding: utf-8 -*-
"""gcd_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dReWSUtDSCT4PsLmN5u-75eoKww7JSaY
"""

# Euclid's Algorithm, even better
def gcd(m,n):
  if m<n: # Assume,m>=n
    (m,n) = (n,m)

  while (m%n)!=0:
    (m,n) = (n,m%n) # m%n < n, always!

  return n

