# -*- coding: utf-8 -*-
"""gcd_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_RdYyYUdR3lfIL8cbr9N0saBk0lYLbV
"""

def gcd(m,n):
  for i in range(1,min(m,n)+1):
    if (m%i)==0 and (n%i)==0:
      mrcf=i
  return mrcf

