# -*- coding: utf-8 -*-
"""gcd_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9W-lRF0CePRKtfQtr08vzKWTHvRcQRK
"""

# Euclid's Algorithm, again
def gcd(m,n):
  if m<n: # Assume m>=n
    (m,n) = (n,m)

  if (m%n)==0:
    return n
  else:
    return gcd(n,m%n) # m%n < n always!

