# -*- coding: utf-8 -*-
"""gcd_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/195FsYjSHDLOQJjyES0sMbn6MMcORvp2j
"""

def gcd(m,n):
  i = min(m,n)

  while i>0:
    if (m%i)==0 and (n%i)==0:
      return(i)
    else:
      i=i-1