# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-P7WPHbBL_3t8IWJxnMGs2JoM3eTay0
"""

# Euclid's Algorithm
def gcd(m,n):
  # Assume m>=n
  if m<n:
    (m,n)=(n,m)
  
  if (m%n)==0:
    return (n)
  else:
    diff=m-n
    # diff > n? Possible!
    return (gcd(max(n,diff),min(n,diff)))