# -*- coding: utf-8 -*-
"""gcd_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j1EoyctqH3IkrXjbHonvHTdzccrR_9IB
"""

# Euclid's Algorithm, revisited
def gcd(m,n):
  if m<n: # Assume, m>=n
    (m,n) = (n,m)
  
  while (m%n)!=0:
    diff = m-n
    # diff > n? Possible!
    (m,n) = (max(n,diff),min(n,diff))
  return n

