# -*- coding: utf-8 -*-
"""Quick Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3sgw5IfraO2NfUVCD-MiW1_-JNFVuLo
"""

def quicksort(A,l,r): # Sort A[l:r]
  if r-l<=1: # Base case
    return()

  # Partition with respect to pivot A[l]
  yellow = l+1

  for green in range(l+1,r):
    if A[green]<=A[l]:
      (A[yellow],A[green]) = (A[green],A[yellow])
      yellow = yellow+1

  # Move pivot into place
  (A[l],A[yellow-1]) = (A[yellow-1],A[l])

  quicksort(A,l,yellow-1) # Recursive calls
  quicksort(A,yellow,r)
  return A

# A = [1,3,2,5,2,9]
# l = 0
# r = 6
# quicksort(A,l,r)

