# -*- coding: utf-8 -*-
"""Recursion_factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3sgw5IfraO2NfUVCD-MiW1_-JNFVuLo
"""

def factorial(n):
  if n==0:
    return 1
  else:
    return (n*factorial(n-1))

