# -*- coding: utf-8 -*-
"""Recursive Insertion Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3sgw5IfraO2NfUVCD-MiW1_-JNFVuLo
"""

def in_sort(seq):
  isort(seq,len(seq))
  return seq

def isort(seq,k):  # Sort slice seq[0:k]
  if k>1:
    isort(seq,k-1)
    insert(seq,k-1)

def insert(seq,k): # Insert seq[k] into sorted seq[0:k-1]
  pos = k
  while pos>0 and seq[pos]<seq[pos-1]:
    (seq[pos],seq[pos-1]) = (seq[pos-1],seq[pos])
    pos = pos-1

# seq = [1,3,2,5,2,9]
# in_sort(seq)

