# -*- coding: utf-8 -*-
"""Searching_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Klm43uSorvAWDoerK-Tr6QGJn2kWA24p
"""

# Search for a value in a list
def findpos(l,v):
  for i in range(len(l)):
    if l[i]==v: # Exit, report position
      pos = i
      break
  else:
    pos = -1 # No break, v not in l
  return pos

# l=[1,3,2,5,2,9]
# v=2

