# -*- coding: utf-8 -*-
"""Searching_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BIXJdfq3sk680KjwxfdFyAxShj-chKK
"""

# Search for a value in a list
def findpos(l,v):
  pos = -1
  for i in range(len(l)):
    if l[i]==v: # Exit, report position
      pos = i
      break
  
  # If pos not reset in loop, pos is -1
  return pos

# l=[1,3,2,5,2,9]
# v=2

